Issue51 @family
inbo/inborutils pull request #109
Opened 2021-04-01 13:39 UTC by RCinbo

'has_concept("keyword")' toegevoegd in de yaml
@family keyword toegevoegd in ieder van de R scripts in de package

2021-04-01 14:04 UTC, hansvancalster requested changes
Great! Looks good. If you accept my suggestions online, can you also rerun `devtools::document` after pulling the remote changes?

2021-04-01 14:04 UTC, hansvancalster commented on R/read_kmi_data.R
> +#' @family download functions
```suggestion
#' @family download_functions
```

2021-04-01 14:04 UTC, hansvancalster commented on R/read_kml_file.R
> +#' @family download functions
```suggestion
#' @family download_functions
```

2021-04-01 14:04 UTC, hansvancalster commented on R/read_knmi_data.R
> +#' @family download functions
```suggestion
#' @family download_functions
```

2021-04-01 14:04 UTC, hansvancalster commented on R/read_mow_data.R
> +#' @family download functions
```suggestion
#' @family download_functions
```

2021-04-01 14:04 UTC, hansvancalster commented on _pkgdown.yml
>        - has_concept("download")
```suggestion
      - has_concept("download_functions")
```

2021-04-01 14:08 UTC, hansvancalster approved these changes

2021-04-01 14:13 UTC, hansvancalster commented
closes #51

2021-04-01 14:17 UTC, hansvancalster commented
closes #34

2021-04-01 14:26 UTC, hansvancalster commented
@damianooldoni @niconoe can you have a look at the failing checks? Looks like they have to do with failing unit tests for `gbif_species_name_match` and `setup_coding_club_session`

2021-04-01 19:59 UTC, damianooldoni commented
Thanks @hansvancalster, it is on my to do list of tomorrow!

2021-04-02 11:47 UTC, damianooldoni commented
@hansvancalster: I removed the section with the three failing tests as they are not really important.

2021-04-06 07:46 UTC, merged