correction of typo 'OrignalName' to 'OriginalName' in recording-function
inbo/inborutils pull request #75
Opened 2020-02-18 16:20 UTC by ElsDeBie

- correction of typo 'OrignalName' in the recording-function
- added possibility to chose the qualifier_type (site or management), comparable as rec_type in header-function and added differentiation in QualifierCode and QualifierDescription by adding Q1, Q2, Q3 in qualifier-function
- added possibility to get information of more than one suvey and added 'Observer' in the header-function

2020-02-19 07:32 UTC, hansvancalster requested changes
Very good improvements! Can you address the requested changes?

2020-02-19 07:32 UTC, hansvancalster commented on R/inboveg_header.R
> +#' @param survey_name A character string or a character vector, depending on multiple parameter,
```suggestion
#' @param survey_name A character string or a character vector  
```

2020-02-19 07:32 UTC, hansvancalster commented on R/inboveg_header.R
> +#' include wildcarts to allow partial matches
```suggestion
#' include wildcards to allow partial matches
```

2020-02-19 08:36 UTC, hansvancalster commented
@ElsDeBie can you also change the letter "é" in `inboveg_recording()` to "\u00E9". Otherwise é will not be displayed correctly in the help file. To make the help files:
````
install.packages("roxygen2") #just make sure you have version 7.0.2
roxygen2::roxygenise()
````

After that is done, also commit the newly created inboveg_*.Rd files and push them to this branch.

2020-02-19 09:27 UTC, florisvdh commented
@hansvancalster did you test the 'é' conversion? That trick not work [here](https://github.com/inbo/inborutils/pull/66).

2020-02-19 10:09 UTC, hansvancalster commented
Indeed, forgot that that didn't work. But it is circumvented now by ee1cdec

2020-02-20 06:49 UTC, hansvancalster approved these changes

2020-02-20 06:49 UTC, merged